### ISSUE TITLE
🚀 Feature: Footer and Social Media Icons In the bottom

### ISSUE THREAD

**Issue by HridoyHazard** [AndrGab/medirepoWeb#100]
### 🔖 Feature description

Footer and Social Media Icons In the bottom

### 🎤 Why is this feature needed ?

it's useful

### ✌️ How do you aim to achieve this?

by coding 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/andrgab/medirepoweb/blob/main/CONTRIBUTING.md)

### 🏢 Have you read the Code of condute

- [X] I have read the [Code of condute](https://github.com/andrgab/medirepoweb/blob/main/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by AndrGab** [comment]
Be my guest. 
Happy to have u here.

**Comment by anushkamandal25** [comment]
hello! @AndrGab Can I work in this issue?

**Comment by AndrGab** [comment]
for sure. Feel free to contribute
