### ISSUE TITLE
Add Malayalam

### ISSUE THREAD

**Issue by AndrGab** [AndrGab/medirepoWeb#103]
Hi, @AndrGab 
I can add Malayalam to this
pls assign me

_Originally posted by @Rinshin-Jalal in https://github.com/AndrGab/medirepoWeb/issues/76#issuecomment-1272448725_

**Comment by Rinshin-Jalal** [comment]
pls assign me
I'm doing it

**Comment by Rinshin-Jalal** [comment]
Completed 

#106
