### ISSUE TITLE
[Hacktoberfest] Add Assamese

### ISSUE THREAD

**Issue by AndrGab** [AndrGab/medirepoWeb#109]
@AndrGab Dear Sir,i want to add Assamese,please assign me sir

_Originally posted by @nidhish-srivastava in https://github.com/AndrGab/medirepoWeb/issues/76#issuecomment-1272611155_

**Comment by das-amit** [comment]
Hey @AndrGab is this issue still open?
I would like to make a PR. Thank You.

**Comment by AndrGab** [comment]
thanks @das-amit 
PR merged 🎉
