### ISSUE TITLE
Feat: Add Urdu

### ISSUE THREAD

**Issue by AndrGab** [AndrGab/medirepoWeb#116]
@AndrGab I would like to add Urdu.
Kindly assign me.

_Originally posted by @kavania2002 in https://github.com/AndrGab/medirepoWeb/issues/76#issuecomment-1274471237_

**Comment by kavania2002** [comment]
Thanks for the opening the issue.
It would be great if you could assign it to me and add the hacktoberfest label.

**Comment by AndrGab** [comment]
done!
