### ISSUE TITLE
Dark mode issue

### ISSUE THREAD

**Issue by AndrGab** [AndrGab/medirepoWeb#12]
After logout darkmode does'nt work.
Trouble with Context.

**Comment by Adityagupta1625** [comment]
I can try to solve this. Please assign this to me.

**Comment by AndrGab** [comment]
Nice. You are Welcome. You can fork this repository and submit you solution.
Thanks.

**Comment by arp99** [comment]
I want to solve this issue, can you just give test credentials to login, I don't know the language.

**Comment by AndrGab** [comment]
Hi,
in login for Hospitals use:

Login: test@email.com
pwd: 123456

Thx

**Comment by arp99** [comment]
@AndrGab I have added a PR #20, Kindly please review the PR 😅

**Comment by AndrGab** [comment]
Thanks

**Comment by arp99** [comment]
> Thanks

You are welcome 😅😅😅
