### ISSUE TITLE
[UI Improvement] : The login page may need a few css changes.

### ISSUE THREAD

**Issue by kushchoudhary98** [AndrGab/medirepoWeb#162]
### 🔖 Feature description

The login page definitely needs a few UI improvements.
Something like this one...
![Screenshot 2024-10-19 at 11 38 40 PM](https://github.com/user-attachments/assets/d1db438c-aa1d-42c6-ba15-74951027f45b)

### 🎤 Why is this feature needed ?

The login page, as for now looks like this..
![Screenshot 2024-10-19 at 11 25 12 PM](https://github.com/user-attachments/assets/b4c91cd9-8de4-4a50-b386-f60945ee4835)

And will look good after the design improvement.

### ✌️ How do you aim to achieve this?

By changing a few CSS properties and adding some new ones.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/andrgab/medirepoweb/blob/main/CONTRIBUTING.md)

### 🏢 Have you read the Code of conduct

- [X] I have read the [Code of conduct](https://github.com/andrgab/medirepoweb/blob/main/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by arun0452** [comment]
Assign this issue to me, Let me fix this

**Comment by Nexusrex18** [comment]
yeah I can improve this login page ,assign it to me plz for hacktoberfest

**Comment by AndrGab** [comment]
thank you guys, please send a PR ❤️

**Comment by arun0452** [comment]
I have already started my work. We split up the work and deliver together @Nexusrex18 ?

**Comment by kushchoudhary98** [comment]
I was facing an error, but anyway, if @arun0452 has already started work. @Nexusrex18 you guys continue.
I'm unassigning myself.
