### ISSUE TITLE
🚀 Feature: Add Zod Library

### ISSUE THREAD

**Issue by Aneeshaik** [AndrGab/medirepoWeb#163]
### 🔖 Feature description

Using Zod, a popular schema declaration and validation library, developers can enforce proper email & password format and consistency between email fields & password fields easily.

### 🎤 Why is this feature needed ?

Validating user input is crucial in any web application to maintain data integrity and provide a good user experience. Email validation is particularly important as it directly impacts user notifications, password resets, and communication channels. Password validation is also an important factor to let user set the strong password for his/her account in our website.

### ✌️ How do you aim to achieve this?

I would like to achieve this by adding Zod Library to our Web App. By using email and password validations in zod library. Please assign to me this issue under hacktoberfest to proceed. Thank You!

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/andrgab/medirepoweb/blob/main/CONTRIBUTING.md)

### 🏢 Have you read the Code of conduct

- [X] I have read the [Code of conduct](https://github.com/andrgab/medirepoweb/blob/main/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by AndrGab** [comment]
thanks, be my guest!

**Comment by Aneeshaik** [comment]
> thanks, be my guest!

Thank you! working on it
