### ISSUE TITLE
[Hacktoberfest] Add i18n lib

### ISSUE THREAD

**Issue by AndrGab** [AndrGab/medirepoWeb#22]
You can install i18n lib and help people to create new translations

**Comment by cimok2000** [comment]
hi I'd like to contribute to adding i18n into the project, thanks.

**Comment by kalwabed** [comment]
Hi, can I work on this?

**Comment by AndrGab** [comment]
please, be my guest

**Comment by AndrGab** [comment]
@kalwabed i18n was added

now you can add you language to the project
https://github.com/AndrGab/medirepoWeb/blob/main/src/i18n.js
