### ISSUE TITLE
Add a how-to-setup guide for setting up the project locally

### ISSUE THREAD

**Issue by spykelionel** [AndrGab/medirepoWeb#25]
How to set up the project locally

**Comment by Gyshie** [comment]
Hi, @AndrGab if you can provide me with the how-to set-up guide in-brief, I will create a meaningful document (guide).

**Comment by AndrGab** [comment]
Hi @Gyshie,
The setup for this project is very simple...

after fork/clone
use ` npm install `  to install libs
start project with ` npm start`

the developer can create an enviroment variable like `.env-sample` file in the project root folder to set the backend host 

I'll appreciate If you could write it down to readme file
Thank you very much

**Comment by Gyshie** [comment]
Sure I'll do it.

**Comment by AndrGab** [comment]
Thx @Gyshie 
You're doing a great job here
🚀
