### ISSUE TITLE
Empty bulletin files are being downloaded

### ISSUE THREAD

**Issue by spykelionel** [AndrGab/medirepoWeb#26]
![bulletin-medical](https://user-images.githubusercontent.com/59184392/193450156-dd7dfa25-924e-4cbd-9662-e04bcec33fce.png)

Try to download a bulletin, downloads an empty file. A proper message should be displayed for a blank bulletin.
[tableDownload.csv](https://github.com/AndrGab/medirepoWeb/files/9692275/tableDownload.csv)

**Comment by dshubhadeep** [comment]
Hi @AndrGab 
Could you assign this to me ?

**Comment by AndrGab** [comment]
Sure.. happy to have you here

**Comment by dshubhadeep** [comment]
Looked into the issue, according to [mui documentation](https://www.npmjs.com/package/mui-datatables) there is a `download` key in the options which takes either string or boolean value.

So based on size of the rows array, we could set the `download` key in options object in [Bulletin.js](https://github.com/AndrGab/medirepoWeb/blob/main/src/pages/hospitals/app/Bulletin.js#L126) as -  
```js
const options = {
//...
download: rows.length ? true : 'disabled',
// ... 
}
```

Please let me know if you are fine with this approach.

**Comment by AndrGab** [comment]
nice, I'm fine with that

**Comment by AndrGab** [comment]
hi @dshubhadeep 
how are u you?
Can you complete the task?
thank you very much

**Comment by dshubhadeep** [comment]
@AndrGab apologies for the delay
I've created the PR
