### ISSUE TITLE
[hacktoberfest] Fix request payload

### ISSUE THREAD

**Issue by AndrGab** [AndrGab/medirepoWeb#27]
We had an update in Backend and now the fields from request are in english.
Need changing.

https://github.com/AndrGab/MediRepo/pull/13

**Comment by gokhalevedant06** [comment]
Hello @AndrGab, I would like to work on this issue

**Comment by AndrGab** [comment]
please...be my guest

**Comment by gokhalevedant06** [comment]
I am getting this error when I try to run the project. I think there is some issue with package.json

![image](https://user-images.githubusercontent.com/79954118/193542805-518138e4-f846-443f-b1f1-95fb460da595.png)

**Comment by AndrGab** [comment]
here, it's working fine.
Please, try do delete all node_modules folder
and reinstall with `npm install`
and start with `npm start`

**Comment by AndrGab** [comment]
it's done...

Feel free  to add a new feature or lib.
