### ISSUE TITLE
[hacktoberfest] translate i18n to your language

### ISSUE THREAD

**Issue by AndrGab** [AndrGab/medirepoWeb#33]
Any language is welcome

Add you language to the project

https://github.com/AndrGab/medirepoWeb/blob/main/src/i18n.js

already included:
- [x] Portuguese
- [x] English
- [x] Spanish
- [x] French
- [x] Marathi
- [x] Polish
- [x] Indonesian
- [x] Mandarin
- [x] Tamil
- [x] German
- [x] Finnish

**Comment by pblop** [comment]
Hey! I'm able to translate it to Spanish, I can PR in a couple of hours!

**Comment by alexsam29** [comment]
Hi, I can try to translate to French.  Not my native language, but I can give it a go.

**Comment by AndrGab** [comment]
nice, thank you guys

**Comment by chatterjeedeep08** [comment]
Hi, I can translate to Hindi, German, Bengali

**Comment by AndrGab** [comment]
Hi @chatterjeedeep08 feel free to add a new language

**Comment by AndrGab** [comment]
This is still opened 'cause we can add more languages, the browser detector is actived now.
and please  ⭐  STAR this repository 😉

**Comment by KIET7UKE** [comment]
Hey, @AndrGab I want to contribute to Translation in Odia, It's our native language in the state of India "Odisha".

**Comment by AndrGab** [comment]
nice, feel free to add Odisha too ❤️

**Comment by WojciechSzade** [comment]
Hey, I can try my best to add polish to your project. I'm new to open source tho, so I would require some guidance.
If you're interested you can dm me :)
https://wojciechszade.github.io/Profile-card/

**Comment by AndrGab** [comment]
> Hey, I can try my best to add polish to your project. I'm new to open source tho, so I would require some guidance. If you're interested you can dm me :) https://wojciechszade.github.io/Profile-card/

hi @WojciechSzade I'm glad to have you here.
the implementation is very simple, just translate the resource const in the module https://github.com/AndrGab/medirepoWeb/blob/main/src/i18n.js to your language

**Comment by thomascouto** [comment]
I can add Portuguese lang if you need

**Comment by AndrGab** [comment]
> I can add Portuguese lang if you need
Hi, @thomascouto 
sorry, portuguese is already included

**Comment by sohampathak1234** [comment]
Hey @AndrGab ! 
I can translate into  "Marathi" lang as it is my native language.

**Comment by AndrGab** [comment]
> Hey @AndrGab ! I can translate into "Marathi" lang as it is my native language.

nice, thx

**Comment by WojciechSzade** [comment]
@AndrGab I have a couple problems:
-Name is name and surname, right?
-In what context is "of" being used?
-What do you mean by "The credentials are informed by the hospital. Ask in the reception."? What are the credentials in this context?

>Name is name and surname, right?
 yes, it's right
> -In what context is "of" being used?
It's used in the table pagination, page 1 "of" 50
> What do you mean by "The credentials are informed by the hospital. Ask in the reception."? What are the credentials in this context?
You can change "The credencials" by "ID and Password". It's going to be used by family mamber to access patient information

thx ;-)

**Comment by AndrGab** [comment]
Please guys and girls ❤️ ... star the repository ⭐ and put a smile on my face 😃

**Comment by Gw3i** [comment]
Hey @AndrGab,
I could translate it in German if there is still need :)

**Comment by AndrGab** [comment]
> Hey @AndrGab, I could translate it in German if there is still need :)

Hi @Gw3i welcome to the team... A German translation should be good.
Please join us

**Comment by jagg2** [comment]
Hi @AndrGab,
If your interested I would like to try and add Esperanto translation.

Wikipedia:  https://en.wikipedia.org/wiki/Esperanto

**Comment by AndrGab** [comment]
> Hi @AndrGab, If your interested I would like to try and add Esperanto translation.
> 
> Wikipedia: https://en.wikipedia.org/wiki/Esperanto

hi @jagg2 feel free to contribute
We are happy you're joinning us

**Comment by dwiki48** [comment]
Hey,,
I can add Indonesia if there is still need hehe

**Comment by AndrGab** [comment]
> Hey,, I can add Indonesia if there is still need hehe

Sure,  make a PR please 😄

**Comment by RTHKKona** [comment]
Hello! I can translate it into mandarin if you'd like. If so, I can get on that immediately once I'm assigned.

**Comment by AndrGab** [comment]
> Hello! I can translate it into mandarin if you'd like. If so, I can get on that immediately once I'm assigned.

Wow, mandarin is great, join us please

**Comment by ArunBalajiR** [comment]
Hi, I can translate into "Tamil" language as it is my native language.

**Comment by AndrGab** [comment]
Welcome @ArunBalajiR

**Comment by youssefkhaled08** [comment]
I can translate into Arabic if you're interested.

**Comment by devnullone** [comment]
> Hi, I can try to translate to French. Not my native language, but I can give it a go.

I check your translation and you did great work!

**Comment by devnullone** [comment]
> nice, thank you guys

I saw some mistakes in the french translation, I made a review to correct that!

**Comment by Rkpani05** [comment]
> nice, feel free to add Odisha too ❤️

I can addin Odia plese assign me

**Comment by Heismanish** [comment]
Hey @AndrGab , I would like to translate it into my native language "Hindi", if that hasn't been done already that is.

**Comment by Hogwarter** [comment]
Hi, I could add Finish

**Comment by AndrGab** [comment]
> I can translate into Arabic if you're interested.

@youssefkhaled08 Arabic is welcome too, thanks a lot.

**Comment by AndrGab** [comment]
> > nice, thank you guys
> 
> I saw some mistakes in the french translation, I made a review to correct that!

Hi @devnullone do you wanna make a PR to fix the translations?

**Comment by AndrGab** [comment]
> > nice, feel free to add Odisha too heart
> 
> I can addin Odia plese assign me

HI @Rkpani05 feel free to add Odia

**Comment by AndrGab** [comment]
> Hey @AndrGab , I would like to translate it into my native language "Hindi", if that hasn't been done already that is.

Please feel free to add Hindi, make a PR @Heismanish

**Comment by devnullone** [comment]
> > > nice, thank you guys
> > 
> > 
> > I saw some mistakes in the french translation, I made a review to correct that!
> 
> Hi @devnullone do you wanna make a PR to fix the translations?

Yes, @AndrGab !

**Comment by AndrGab** [comment]
guys and girls ❤️  ... ⭐  the repository please 😉

**Comment by AndrGab** [comment]
@youssefkhaled08 Arabic
@Rkpani05  Odisha
@jagg2 Esperanto
@KIET7UKE Odisha
@chatterjeedeep08 Bengali

Hi guys, I changed the project structure for new languages. It's cleaner now.
Please send us your contribution
The new issue is #76
