### ISSUE TITLE
[hacktoberfest] Create a switch button to change the language

### ISSUE THREAD

**Issue by AndrGab** [AndrGab/medirepoWeb#35]
An i18n lib was installed in the project, now we need a toogle button to change among the installed languages.

Put it on Top right corner, or in the settings menu.

Feel free to put your personal preference.

**Comment by jmmendivil** [comment]
I can help on this one

**Comment by AndrGab** [comment]
nice, would be great

**Comment by AndrGab** [comment]
Hi @jmmendivil 
the i18next lib was installed, you can set a localStorage key "i18nextLng" with the language selected by the user.
Available languages are in const resources in the i18n.js file.
