### ISSUE TITLE
[hacktoberfest] English review in i18n 

### ISSUE THREAD

**Issue by AndrGab** [AndrGab/medirepoWeb#36]
An i18n lib was installed in the project, I'd like some help to review the English Grammars.

**Comment by sudhir512kj** [comment]
@AndrGab I would like to work on this issue.

**Comment by AndrGab** [comment]
feel free to do it, please

**Comment by AndrGab** [comment]
@sudhir512kj do u need some help with that?

**Comment by AndrGab** [comment]
@Gyshie how are you?
Can you help us with this one too?

**Comment by Gyshie** [comment]
@AndrGab Can you mention a link to the relevant file here; that I have to correct grammar?

**Comment by ad-olfo** [comment]
Hi,
Nice little project here :)
I've spotted some mistakes on the internationalization translations, 
I'll create a test account and have a deep look on that.

I'll look at Spanish, French and will also check English (not the base language of the project?).

BTW, one file by language may help you to manage this more easily :shipit:

**Comment by AndrGab** [comment]
> @AndrGab Can you mention a link to the relevant file here; that I have to correct grammar?

in this file @Gyshie 
https://github.com/AndrGab/medirepoWeb/blob/main/src/i18n.js

**Comment by AndrGab** [comment]
@41646F6C666F 
it sounds great, languages numbers are increasing fast 😄 
May I assign that to you?

**Comment by Gyshie** [comment]
> > @AndrGab Can you mention a link to the relevant file here; that I have to correct grammar?
> 
> in this file @Gyshie https://github.com/AndrGab/medirepoWeb/blob/main/src/i18n.js

OK. I'll check it. You want me to correct the grammar and formats in the English translations part, right?

**Comment by AndrGab** [comment]
> > > @AndrGab Can you mention a link to the relevant file here; that I have to correct grammar?
> > 
> > 
> > in this file @Gyshie https://github.com/AndrGab/medirepoWeb/blob/main/src/i18n.js
> 
> OK. I'll check it. You want me to correct the grammar and formats in the English translations part, right?

please, it would be nice

**Comment by ad-olfo** [comment]
Thanks for the proposal @AndrGab, but no need to assign me, like this it will leave open to anyone who will collaborate.
Also, if you are agreeing with the fact to split the languages, you can create a new issue to create more tasks for the users too.

**Comment by AndrGab** [comment]
> Thanks for the proposal @AndrGab, but no need to assign me, like this it will leave open to anyone who will collaborate. Also, if you are agreeing with the fact to split the languages, you can create a new issue to create more tasks for the users too.

@41646F6C666F 
I understand, thanks for your comments. I think your are right, I'm gonna open new issues for that.
I appreciated that. 🤗

**Comment by Gyshie** [comment]
@AndrGab It's done! :)

**Comment by AndrGab** [comment]
Thank you...
