### ISSUE TITLE
Login Icon used instead of Login 

### ISSUE THREAD

**Issue by InternetRamen** [AndrGab/medirepoWeb#51]
Hey I'd love to fix this for hacktoberfest, could you confirm that this is a valid issue?

Login Icons are usually used in Bottom Nav bars and look out of place when placed above a login page. Having a larger text header might look better 👍 

![image](https://user-images.githubusercontent.com/66806100/193958619-832542de-286d-4f06-b372-178f8e479f9c.png)

![image](https://user-images.githubusercontent.com/66806100/193958572-cca884e6-1c07-42fa-b3c3-bed03e295425.png)

**Comment by AndrGab** [comment]
Hi @InternetRamen feel free to fix it! thank you very much

**Comment by InternetRamen** [comment]
#54

**Comment by AndrGab** [comment]
nice job
