### ISSUE TITLE
Show Alert on failed API request

### ISSUE THREAD

**Issue by Pranshu1902** [AndrGab/medirepoWeb#70]
A message saying that the request has been rejected would be visible on the screen.
![image](https://user-images.githubusercontent.com/70687348/194084690-e52ecea8-a2fc-4971-9e3b-a2138347bc01.png)

**Comment by Pranshu1902** [comment]
@AndrGab If you find this a valid issue then please assign it to me

**Comment by AndrGab** [comment]
Go ahead @Pranshu1902 feel free to fix it.
I didn't understand the error... All backend errors was tracked? what was the http code received?

**Comment by Pranshu1902** [comment]
@AndrGab The error was on my end, the API site was blocked that's why it was failing. Sorry for wasting your time. Closing this issue.
