### ISSUE TITLE
Add loader on Profile page

### ISSUE THREAD

**Issue by Pranshu1902** [AndrGab/medirepoWeb#71]
The input fields are empty while the data is being fetched from the API.
https://www.loom.com/share/370ae2e48c424afa9c54775f71e70570

Expected behaviour
Loader should be visible instead of empty input fields.

**Comment by Pranshu1902** [comment]
@AndrGab If you find this issue valid then please assign it to me

**Comment by AndrGab** [comment]
thank you @Pranshu1902 you are doing a great job
