### ISSUE TITLE
Bengali language

### ISSUE THREAD

**Issue by AndrGab** [AndrGab/medirepoWeb#77]
I want to add Bengali language to this folder could you assign me this issue

_Originally posted by @Sayak-singha in https://github.com/AndrGab/medirepoWeb/issues/76#issuecomment-1269216403_

**Comment by Sayak-singha** [comment]
Can I start working on this issue ?

**Comment by Sayak-singha** [comment]
> ```
>     I want to add Bengali language to this folder could you assign me this issue
> ```
> 
> _Originally posted by @Sayak-singha in [#76 (comment)](https://github.com/AndrGab/medirepoWeb/issues/76#issuecomment-1269216403)_

could you please authorize my PR

**Comment by AndrGab** [comment]
Done.
Good Job.
Thank you 🎉
