### ISSUE TITLE
[Hacktoberfest] Feature: A new modal window for changing languages

### ISSUE THREAD

**Issue by AndrGab** [AndrGab/medirepoWeb#96]
### 🔖 Feature description

We have more than 15 languages in the project. The dropdown list now is too big.

### 🎤 Why is this feature needed ?

A modal window should look better.

### ✌️ How do you aim to achieve this?

Adding a new react component with a modal window with languages in buttons 

### 🔄️ Additional Information

![image](https://user-images.githubusercontent.com/57791712/194718490-8b54d468-074c-4dda-9690-7315f73d4c0f.png)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/andrgab/medirepoweb/blob/main/CONTRIBUTING.md)

### 🏢 Have you read the Code of condute

- [X] I have read the [Code of condute](https://github.com/andrgab/medirepoweb/blob/main/CODE_OF_CONDUCT.md)

**Comment by najeebkp** [comment]
Hi @AndrGab  please assign this to me

**Comment by AndrGab** [comment]
thank you 😃
