### ISSUE TITLE
[Hacktoberfest] Bugfix: modal window size

### ISSUE THREAD

**Issue by AndrGab** [AndrGab/medirepoWeb#97]
### 📜 Description

In big screens, the bulletin view has a  window modal bigger than necessary

### 👟 Reproduction steps

1. Click Bulletins
2. Click on a patient to show bulletin

### 👍 Expected behavior

a modal window that fits the bulletin view

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/57791712/194718817-b2fa77da-c7a1-49c7-a548-8d3e8cf4304a.png)

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/andrgab/medirepoweb/blob/main/CONTRIBUTING.md)

### 🏢 Have you read the Code of condute

- [X] I have read the [Code of condute](https://github.com/andrgab/medirepoweb/blob/main/CODE_OF_CONDUCT.md)

**Comment by Bivas-Biswas** [comment]
Hey @AndrGab, looks interesting, can I work on this ??

**Comment by AndrGab** [comment]
Thank you, I've assigned it to you

**Comment by Bivas-Biswas** [comment]
@AndrGab Hello, can give any test login credentials

**Comment by AndrGab** [comment]
Hi @Bivas-Biswas 

hospital
login:
test@gmail.com
password:
123456

patient
login
111222
password
111222
birthday
2022-10-01
hospital:
hospital for Test/test@gmail.com/pass: 123456

you can use these ones

**Comment by AndrGab** [comment]
Thank you very much
